### ISSUE TITLE
autotools is broken

### ISSUE THREAD

**Issue by PandorasFox** [Raymo111/i3lock-color#52]
upstream moved to use autotools in ef4f9e40570d020571d277bde5703e32b126b9e4. Not too bad, but:

* blur stuff is broken (address sanitizer doesn't like it, at least
* I haven't been able to get it to compile a non-address-sanitizing build yet
  * When I try to, it's apparently still inserting the address sanitization hooks, but jk lol no it's no

This'll require a lot of work :V

**Comment by PandorasFox** [comment]
fixed in 9f8496441c777849c31d2a3965dc5168de5fe68b

**Comment by dikiaap** [comment]
I still have this blur problem when building.
OS: Ubuntu 16.04 LTS. 32 bit.

My commands:
```shell
autoreconf -fi
rm -rf build
mkdir build
cd build
../configure
make -j8
```

Sorry for the long log:
```
Already up to date.
configure.ac:101: installing './ar-lib'
configure.ac:53: installing './compile'
configure.ac:7: installing './config.guess'
configure.ac:7: installing './config.sub'
configure.ac:8: installing './install-sh'
configure.ac:8: installing './missing'
Makefile.am: installing './depcomp'
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
checking target system type... i686-pc-linux-gnu
checking for gsed... sed
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for gawk... (cached) gawk
checking for GNU make... make
checking for a sed that does not truncate output... /bin/sed
checking whether to build with code coverage support... no
checking whether to enable debugging... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for mode_t... yes
checking for off_t... yes
checking for pid_t... yes
checking for size_t... yes
checking for ssize_t... yes
checking for pid_t... (cached) yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking whether lstat correctly handles trailing slash... yes
checking for working strnlen... yes
checking for atexit... yes
checking for dup2... yes
checking for ftruncate... yes
checking for getcwd... yes
checking for gettimeofday... yes
checking for localtime_r... yes
checking for memchr... yes
checking for memset... yes
checking for mkdir... yes
checking for rmdir... yes
checking for setlocale... yes
checking for socket... yes
checking for strcasecmp... yes
checking for strchr... yes
checking for strdup... yes
checking for strerror... yes
checking for strncasecmp... yes
checking for strndup... yes
checking for strrchr... yes
checking for strspn... yes
checking for strstr... yes
checking for strtol... yes
checking for strtoul... yes
checking for library containing floor... -lm
checking for library containing ev_run... -lev
checking for library containing shm_open... -lrt
checking for library containing pam_authenticate... -lpam
checking for library containing iconv_open... none required
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for XCB... yes
checking for XCB_IMAGE... yes
checking for XCB_UTIL... yes
checking for XKBCOMMON... yes
checking for CAIRO... yes
checking for X11... yes
checking for gawk... (cached) gawk
checking how to run the C preprocessor... gcc -E
checking whether make sets $(MAKE)... (cached) yes
checking for ranlib... ranlib
checking whether ln -s works... yes
checking for ar... ar
checking the archiver (ar) interface... ar
checking CFLAGS for maximum warnings... -Wall
checking whether C compiler accepts -Wunused-value... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking for inttypes.h... (cached) yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking paths.h usability... yes
checking paths.h presence... yes
checking for paths.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking whether C compiler accepts -fsanitize=address... yes
checking whether the linker accepts -fsanitize=address... yes
checking whether C compiler accepts -fno-omit-frame-pointer... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: executing buildir commands
config.status: skipping top_srcdir/Makefile - not created
config.status: executing depfiles commands
--------------------------------------------------------------------------------
build configured:

  i3lock version:         2.10.1c-2-g29251d6 (2017-12-06, branch "master")
  is release version:     no

  enable debug flags:     yes
  code coverage:          no
  enabled sanitizers:     address 

To compile, run:

  cd /home/dikiaap/.local/src/i3lock-color/build && make -j8
--------------------------------------------------------------------------------
make  all-am
make[1]: Entering directory '/home/dikiaap/.local/src/i3lock-color/build'
  CC       i3lock-i3lock.o
  CC       i3lock-randr.o
  CC       i3lock-tinyexpr.o
  CC       i3lock-blur_simd.o
  CC       i3lock-blur.o
  CC       i3lock-unlock_indicator.o
  CC       i3lock-xcb.o
../../i3lock-color/blur.c: In function ‘blur_impl_horizontal_pass_generic’:
../../i3lock-color/blur.c:124:25: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
                     if ((long long) ((src + 4*i - HALF_KERNEL) + 1)
                         ^
../../i3lock-color/blur.c:125:31: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
                             > (long long) (o_src + (height * width)))
                               ^
../../i3lock-color/blur_simd.c: In function ‘blur_impl_horizontal_pass_sse2’:
../../i3lock-color/blur_simd.c:49:25: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
                     if ((long long) (((__m128i*) src + 4*k - HALF_KERNEL) + 1)
                         ^
../../i3lock-color/blur_simd.c:50:31: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
                             > (long long) (o_src + (height * width)))
                               ^
../../i3lock-color/blur_simd.c:38:31: warning: SSE vector return without SSE enabled changes the ABI [-Wpsabi]
                     rgbaIn[k] = _mm_load_si128((__m128i*)(_rgbaIn + 4*k));
                               ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:690:1: error: inlining failed in call to always_inline ‘_mm_load_si128’: target specific option mismatch
 _mm_load_si128 (__m128i const *__P)
 ^
../../i3lock-color/blur_simd.c:38:33: error: called from here
                     rgbaIn[k] = _mm_load_si128((__m128i*)(_rgbaIn + 4*k));
                                 ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:690:1: error: inlining failed in call to always_inline ‘_mm_load_si128’: target specific option mismatch
 _mm_load_si128 (__m128i const *__P)
 ^
../../i3lock-color/blur_simd.c:46:33: error: called from here
                     rgbaIn[k] = _mm_load_si128((__m128i*)(_rgbaIn + 4*k));
                                 ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:696:1: error: inlining failed in call to always_inline ‘_mm_loadu_si128’: target specific option mismatch
 _mm_loadu_si128 (__m128i const *__P)
 ^
../../i3lock-color/blur_simd.c:52:33: error: called from here
                     rgbaIn[k] = _mm_loadu_si128((__m128i*)(src + 4*k - HALF_KERNEL));
                                 ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:219:1: error: inlining failed in call to always_inline ‘_mm_cvtsi128_si32’: target specific option mismatch
 _mm_cvtsi128_si32 (__m128i __A)
 ^
../../i3lock-color/blur_simd.c:75:17: error: called from here
                 _mm_cvtsi128_si32(_mm_packus_epi16(_mm_packs_epi32(acc, zero), zero));
                 ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:957:1: error: inlining failed in call to always_inline ‘_mm_packus_epi16’: target specific option mismatch
 _mm_packus_epi16 (__m128i __A, __m128i __B)
 ^
../../i3lock-color/blur_simd.c:75:17: error: called from here
                 _mm_cvtsi128_si32(_mm_packus_epi16(_mm_packs_epi32(acc, zero), zero));
                 ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:951:1: error: inlining failed in call to always_inline ‘_mm_packs_epi32’: target specific option mismatch
 _mm_packs_epi32 (__m128i __A, __m128i __B)
 ^
../../i3lock-color/blur_simd.c:75:17: error: called from here
                 _mm_cvtsi128_si32(_mm_packus_epi16(_mm_packs_epi32(acc, zero), zero));
                 ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:807:1: error: inlining failed in call to always_inline ‘_mm_cvtps_epi32’: target specific option mismatch
 _mm_cvtps_epi32 (__m128 __A)
 ^
../../i3lock-color/blur_simd.c:71:17: error: called from here
             acc = _mm_cvtps_epi32(_mm_mul_ps(_mm_cvtepi32_ps(acc),
                 ^
In file included from ../../i3lock-color/blur_simd.c:11:0:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:193:1: error: inlining failed in call to always_inline ‘_mm_mul_ps’: target specific option mismatch
 _mm_mul_ps (__m128 __A, __m128 __B)
 ^
../../i3lock-color/blur_simd.c:71:19: error: called from here
             acc = _mm_cvtps_epi32(_mm_mul_ps(_mm_cvtepi32_ps(acc),
                   ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:765:1: error: inlining failed in call to always_inline ‘_mm_cvtepi32_ps’: target specific option mismatch
 _mm_cvtepi32_ps (__m128i __A)
 ^
../../i3lock-color/blur_simd.c:71:19: error: called from here
             acc = _mm_cvtps_epi32(_mm_mul_ps(_mm_cvtepi32_ps(acc),
                   ^
In file included from ../../i3lock-color/blur_simd.c:11:0:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:889:1: error: inlining failed in call to always_inline ‘_mm_set1_ps’: target specific option mismatch
 _mm_set1_ps (float __F)
 ^
../../i3lock-color/blur_simd.c:71:19: error: called from here
             acc = _mm_cvtps_epi32(_mm_mul_ps(_mm_cvtepi32_ps(acc),
                   ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1023:1: error: inlining failed in call to always_inline ‘_mm_add_epi32’: target specific option mismatch
 _mm_add_epi32 (__m128i __A, __m128i __B)
 ^
../../i3lock-color/blur_simd.c:67:17: error: called from here
             acc = _mm_add_epi32(_mm_unpacklo_epi16(acc, zero),
                 ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:993:1: error: inlining failed in call to always_inline ‘_mm_unpacklo_epi16’: target specific option mismatch
 _mm_unpacklo_epi16 (__m128i __A, __m128i __B)
 ^
../../i3lock-color/blur_simd.c:67:19: error: called from here
             acc = _mm_add_epi32(_mm_unpacklo_epi16(acc, zero),
                   ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:969:1: error: inlining failed in call to always_inline ‘_mm_unpackhi_epi16’: target specific option mismatch
 _mm_unpackhi_epi16 (__m128i __A, __m128i __B)
 ^
../../i3lock-color/blur_simd.c:67:19: error: called from here
             acc = _mm_add_epi32(_mm_unpacklo_epi16(acc, zero),
                   ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1017:1: error: inlining failed in call to always_inline ‘_mm_add_epi16’: target specific option mismatch
 _mm_add_epi16 (__m128i __A, __m128i __B)
 ^
../../i3lock-color/blur_simd.c:65:17: error: called from here
             acc = _mm_add_epi16(acc, _mm_andnot_si128(_mm_set_epi32(0xFFFFFFFF, 0xFFFFFFFF, 0, 0),
                 ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1274:1: error: inlining failed in call to always_inline ‘_mm_andnot_si128’: target specific option mismatch
 _mm_andnot_si128 (__m128i __A, __m128i __B)
 ^
../../i3lock-color/blur_simd.c:65:19: error: called from here
             acc = _mm_add_epi16(acc, _mm_andnot_si128(_mm_set_epi32(0xFFFFFFFF, 0xFFFFFFFF, 0, 0),
                   ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:597:1: error: inlining failed in call to always_inline ‘_mm_set_epi32’: target specific option mismatch
 _mm_set_epi32 (int __q3, int __q2, int __q1, int __q0)
 ^
../../i3lock-color/blur_simd.c:65:19: error: called from here
             acc = _mm_add_epi16(acc, _mm_andnot_si128(_mm_set_epi32(0xFFFFFFFF, 0xFFFFFFFF, 0, 0),
                   ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:963:1: error: inlining failed in call to always_inline ‘_mm_unpackhi_epi8’: target specific option mismatch
 _mm_unpackhi_epi8 (__m128i __A, __m128i __B)
 ^
../../i3lock-color/blur_simd.c:65:19: error: called from here
             acc = _mm_add_epi16(acc, _mm_andnot_si128(_mm_set_epi32(0xFFFFFFFF, 0xFFFFFFFF, 0, 0),
                   ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1017:1: error: inlining failed in call to always_inline ‘_mm_add_epi16’: target specific option mismatch
 _mm_add_epi16 (__m128i __A, __m128i __B)
 ^
../../i3lock-color/blur_simd.c:61:17: error: called from here
             acc = _mm_add_epi16(acc, _mm_unpacklo_epi8(rgbaIn[1], zero));
                 ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:987:1: error: inlining failed in call to always_inline ‘_mm_unpacklo_epi8’: target specific option mismatch
 _mm_unpacklo_epi8 (__m128i __A, __m128i __B)
 ^
../../i3lock-color/blur_simd.c:61:19: error: called from here
             acc = _mm_add_epi16(acc, _mm_unpacklo_epi8(rgbaIn[1], zero));
                   ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1017:1: error: inlining failed in call to always_inline ‘_mm_add_epi16’: target specific option mismatch
 _mm_add_epi16 (__m128i __A, __m128i __B)
 ^
../../i3lock-color/blur_simd.c:60:17: error: called from here
             acc = _mm_add_epi16(acc, _mm_unpackhi_epi8(rgbaIn[0], zero));
                 ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:963:1: error: inlining failed in call to always_inline ‘_mm_unpackhi_epi8’: target specific option mismatch
 _mm_unpackhi_epi8 (__m128i __A, __m128i __B)
 ^
../../i3lock-color/blur_simd.c:60:19: error: called from here
             acc = _mm_add_epi16(acc, _mm_unpackhi_epi8(rgbaIn[0], zero));
                   ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1017:1: error: inlining failed in call to always_inline ‘_mm_add_epi16’: target specific option mismatch
 _mm_add_epi16 (__m128i __A, __m128i __B)
 ^
../../i3lock-color/blur_simd.c:59:17: error: called from here
             acc = _mm_add_epi16(acc, _mm_unpacklo_epi8(rgbaIn[0], zero));
                 ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:987:1: error: inlining failed in call to always_inline ‘_mm_unpacklo_epi8’: target specific option mismatch
 _mm_unpacklo_epi8 (__m128i __A, __m128i __B)
 ^
../../i3lock-color/blur_simd.c:59:19: error: called from here
             acc = _mm_add_epi16(acc, _mm_unpacklo_epi8(rgbaIn[0], zero));
                   ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:753:1: error: inlining failed in call to always_inline ‘_mm_setzero_si128’: target specific option mismatch
 _mm_setzero_si128 (void)
 ^
../../i3lock-color/blur_simd.c:57:21: error: called from here
             __m128i acc = _mm_setzero_si128();
                     ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:753:1: error: inlining failed in call to always_inline ‘_mm_setzero_si128’: target specific option mismatch
 _mm_setzero_si128 (void)
 ^
../../i3lock-color/blur_simd.c:56:21: error: called from here
             __m128i zero = _mm_setzero_si128();
                     ^
Makefile:632: recipe for target 'i3lock-blur_simd.o' failed
make[1]: *** [i3lock-blur_simd.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/dikiaap/.local/src/i3lock-color/build'
Makefile:432: recipe for target 'all' failed
make: *** [all] Error 2

 Previous i3lock version: 

───────────────────────────────────────────────────────────────────────────
i3lock: version 2.10.1-c (2017-11-29) © 2010 Michael Stapelberg
───────────────────────────────────────────────────────────────────────────

 Installing i3lock & i3lock-fancy... 

  CC       i3lock-blur_simd.o
../../i3lock-color/blur_simd.c: In function ‘blur_impl_horizontal_pass_sse2’:
../../i3lock-color/blur_simd.c:49:25: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
                     if ((long long) (((__m128i*) src + 4*k - HALF_KERNEL) + 1)
                         ^
../../i3lock-color/blur_simd.c:50:31: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
                             > (long long) (o_src + (height * width)))
                               ^
../../i3lock-color/blur_simd.c:38:31: warning: SSE vector return without SSE enabled changes the ABI [-Wpsabi]
                     rgbaIn[k] = _mm_load_si128((__m128i*)(_rgbaIn + 4*k));
                               ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:690:1: error: inlining failed in call to always_inline ‘_mm_load_si128’: target specific option mismatch
 _mm_load_si128 (__m128i const *__P)
 ^
../../i3lock-color/blur_simd.c:38:33: error: called from here
                     rgbaIn[k] = _mm_load_si128((__m128i*)(_rgbaIn + 4*k));
                                 ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:690:1: error: inlining failed in call to always_inline ‘_mm_load_si128’: target specific option mismatch
 _mm_load_si128 (__m128i const *__P)
 ^
../../i3lock-color/blur_simd.c:46:33: error: called from here
                     rgbaIn[k] = _mm_load_si128((__m128i*)(_rgbaIn + 4*k));
                                 ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:696:1: error: inlining failed in call to always_inline ‘_mm_loadu_si128’: target specific option mismatch
 _mm_loadu_si128 (__m128i const *__P)
 ^
../../i3lock-color/blur_simd.c:52:33: error: called from here
                     rgbaIn[k] = _mm_loadu_si128((__m128i*)(src + 4*k - HALF_KERNEL));
                                 ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:219:1: error: inlining failed in call to always_inline ‘_mm_cvtsi128_si32’: target specific option mismatch
 _mm_cvtsi128_si32 (__m128i __A)
 ^
../../i3lock-color/blur_simd.c:75:17: error: called from here
                 _mm_cvtsi128_si32(_mm_packus_epi16(_mm_packs_epi32(acc, zero), zero));
                 ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:957:1: error: inlining failed in call to always_inline ‘_mm_packus_epi16’: target specific option mismatch
 _mm_packus_epi16 (__m128i __A, __m128i __B)
 ^
../../i3lock-color/blur_simd.c:75:17: error: called from here
                 _mm_cvtsi128_si32(_mm_packus_epi16(_mm_packs_epi32(acc, zero), zero));
                 ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:951:1: error: inlining failed in call to always_inline ‘_mm_packs_epi32’: target specific option mismatch
 _mm_packs_epi32 (__m128i __A, __m128i __B)
 ^
../../i3lock-color/blur_simd.c:75:17: error: called from here
                 _mm_cvtsi128_si32(_mm_packus_epi16(_mm_packs_epi32(acc, zero), zero));
                 ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:807:1: error: inlining failed in call to always_inline ‘_mm_cvtps_epi32’: target specific option mismatch
 _mm_cvtps_epi32 (__m128 __A)
 ^
../../i3lock-color/blur_simd.c:71:17: error: called from here
             acc = _mm_cvtps_epi32(_mm_mul_ps(_mm_cvtepi32_ps(acc),
                 ^
In file included from ../../i3lock-color/blur_simd.c:11:0:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:193:1: error: inlining failed in call to always_inline ‘_mm_mul_ps’: target specific option mismatch
 _mm_mul_ps (__m128 __A, __m128 __B)
 ^
../../i3lock-color/blur_simd.c:71:19: error: called from here
             acc = _mm_cvtps_epi32(_mm_mul_ps(_mm_cvtepi32_ps(acc),
                   ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:765:1: error: inlining failed in call to always_inline ‘_mm_cvtepi32_ps’: target specific option mismatch
 _mm_cvtepi32_ps (__m128i __A)
 ^
../../i3lock-color/blur_simd.c:71:19: error: called from here
             acc = _mm_cvtps_epi32(_mm_mul_ps(_mm_cvtepi32_ps(acc),
                   ^
In file included from ../../i3lock-color/blur_simd.c:11:0:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:889:1: error: inlining failed in call to always_inline ‘_mm_set1_ps’: target specific option mismatch
 _mm_set1_ps (float __F)
 ^
../../i3lock-color/blur_simd.c:71:19: error: called from here
             acc = _mm_cvtps_epi32(_mm_mul_ps(_mm_cvtepi32_ps(acc),
                   ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1023:1: error: inlining failed in call to always_inline ‘_mm_add_epi32’: target specific option mismatch
 _mm_add_epi32 (__m128i __A, __m128i __B)
 ^
../../i3lock-color/blur_simd.c:67:17: error: called from here
             acc = _mm_add_epi32(_mm_unpacklo_epi16(acc, zero),
                 ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:993:1: error: inlining failed in call to always_inline ‘_mm_unpacklo_epi16’: target specific option mismatch
 _mm_unpacklo_epi16 (__m128i __A, __m128i __B)
 ^
../../i3lock-color/blur_simd.c:67:19: error: called from here
             acc = _mm_add_epi32(_mm_unpacklo_epi16(acc, zero),
                   ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:969:1: error: inlining failed in call to always_inline ‘_mm_unpackhi_epi16’: target specific option mismatch
 _mm_unpackhi_epi16 (__m128i __A, __m128i __B)
 ^
../../i3lock-color/blur_simd.c:67:19: error: called from here
             acc = _mm_add_epi32(_mm_unpacklo_epi16(acc, zero),
                   ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1017:1: error: inlining failed in call to always_inline ‘_mm_add_epi16’: target specific option mismatch
 _mm_add_epi16 (__m128i __A, __m128i __B)
 ^
../../i3lock-color/blur_simd.c:65:17: error: called from here
             acc = _mm_add_epi16(acc, _mm_andnot_si128(_mm_set_epi32(0xFFFFFFFF, 0xFFFFFFFF, 0, 0),
                 ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1274:1: error: inlining failed in call to always_inline ‘_mm_andnot_si128’: target specific option mismatch
 _mm_andnot_si128 (__m128i __A, __m128i __B)
 ^
../../i3lock-color/blur_simd.c:65:19: error: called from here
             acc = _mm_add_epi16(acc, _mm_andnot_si128(_mm_set_epi32(0xFFFFFFFF, 0xFFFFFFFF, 0, 0),
                   ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:597:1: error: inlining failed in call to always_inline ‘_mm_set_epi32’: target specific option mismatch
 _mm_set_epi32 (int __q3, int __q2, int __q1, int __q0)
 ^
../../i3lock-color/blur_simd.c:65:19: error: called from here
             acc = _mm_add_epi16(acc, _mm_andnot_si128(_mm_set_epi32(0xFFFFFFFF, 0xFFFFFFFF, 0, 0),
                   ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:963:1: error: inlining failed in call to always_inline ‘_mm_unpackhi_epi8’: target specific option mismatch
 _mm_unpackhi_epi8 (__m128i __A, __m128i __B)
 ^
../../i3lock-color/blur_simd.c:65:19: error: called from here
             acc = _mm_add_epi16(acc, _mm_andnot_si128(_mm_set_epi32(0xFFFFFFFF, 0xFFFFFFFF, 0, 0),
                   ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1017:1: error: inlining failed in call to always_inline ‘_mm_add_epi16’: target specific option mismatch
 _mm_add_epi16 (__m128i __A, __m128i __B)
 ^
../../i3lock-color/blur_simd.c:61:17: error: called from here
             acc = _mm_add_epi16(acc, _mm_unpacklo_epi8(rgbaIn[1], zero));
                 ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:987:1: error: inlining failed in call to always_inline ‘_mm_unpacklo_epi8’: target specific option mismatch
 _mm_unpacklo_epi8 (__m128i __A, __m128i __B)
 ^
../../i3lock-color/blur_simd.c:61:19: error: called from here
             acc = _mm_add_epi16(acc, _mm_unpacklo_epi8(rgbaIn[1], zero));
                   ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1017:1: error: inlining failed in call to always_inline ‘_mm_add_epi16’: target specific option mismatch
 _mm_add_epi16 (__m128i __A, __m128i __B)
 ^
../../i3lock-color/blur_simd.c:60:17: error: called from here
             acc = _mm_add_epi16(acc, _mm_unpackhi_epi8(rgbaIn[0], zero));
                 ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:963:1: error: inlining failed in call to always_inline ‘_mm_unpackhi_epi8’: target specific option mismatch
 _mm_unpackhi_epi8 (__m128i __A, __m128i __B)
 ^
../../i3lock-color/blur_simd.c:60:19: error: called from here
             acc = _mm_add_epi16(acc, _mm_unpackhi_epi8(rgbaIn[0], zero));
                   ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1017:1: error: inlining failed in call to always_inline ‘_mm_add_epi16’: target specific option mismatch
 _mm_add_epi16 (__m128i __A, __m128i __B)
 ^
../../i3lock-color/blur_simd.c:59:17: error: called from here
             acc = _mm_add_epi16(acc, _mm_unpacklo_epi8(rgbaIn[0], zero));
                 ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:987:1: error: inlining failed in call to always_inline ‘_mm_unpacklo_epi8’: target specific option mismatch
 _mm_unpacklo_epi8 (__m128i __A, __m128i __B)
 ^
../../i3lock-color/blur_simd.c:59:19: error: called from here
             acc = _mm_add_epi16(acc, _mm_unpacklo_epi8(rgbaIn[0], zero));
                   ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:753:1: error: inlining failed in call to always_inline ‘_mm_setzero_si128’: target specific option mismatch
 _mm_setzero_si128 (void)
 ^
../../i3lock-color/blur_simd.c:57:21: error: called from here
             __m128i acc = _mm_setzero_si128();
                     ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:1249:0,
                 from ../../i3lock-color/blur_simd.c:11:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:753:1: error: inlining failed in call to always_inline ‘_mm_setzero_si128’: target specific option mismatch
 _mm_setzero_si128 (void)
 ^
../../i3lock-color/blur_simd.c:56:21: error: called from here
             __m128i zero = _mm_setzero_si128();
                     ^
Makefile:632: recipe for target 'i3lock-blur_simd.o' failed
make: *** [i3lock-blur_simd.o] Error 1
```

**Comment by PandorasFox** [comment]
oh, hm, 32-bit device without SSE2 support?

I should have a fix for this in an hour or so

**Comment by PandorasFox** [comment]
Should be fixed in 4318dbe05142dd7229d4b44565b482ed50a7c381

**Comment by dikiaap** [comment]
Great. Thank you!
