### ISSUE TITLE
Status text position

### ISSUE THREAD

**Issue by Trollwut** [Raymo111/i3lock-color#56]
Any plans on integrating a `--statuspos` similar to those for the date string and clock? :)

**Comment by PandorasFox** [comment]
It'll require a bit more work since it needs to be decoupled from the regular ring indicator (currently, on the bar indicator, there's no way to see the status text).

I'll have to poke at it a bit later, and it's been on my mind, but it's more annoying to implement than the rest.

**Comment by Trollwut** [comment]
Ah ok, so it's not a thing for the near future. :)

Was asking because I currently use [`betterlockscreen`](https://github.com/pavanjadhaw/betterlockscreen), which bases on `i3lock-color` and it would be nice to have the status text added in that "textbox" instead of only one letter in that small circle :D

**Comment by PandorasFox** [comment]
I'll definitely look into it after I do some other refactoring this weekend

**Comment by AUTplayed** [comment]
mod position would also be nice, because if the radius is < 30 you can't really see the "caps lock" warning

**Comment by PandorasFox** [comment]
Yeah, I need to work on this soon, but I ended up being ill for most of December, and now school is starting back up again p:

This is something I've been meaning to do for a while (but have been hesitant to do so, because it'll make this fork a bit more of a hard fork from upstream / harder to maintain), so if I'm going to be doing this, I'll be doing a decent amount of refactoring to make this more maintainable.

**Comment by AUTplayed** [comment]
sure, take your time, just wanted to mention it :)

**Comment by PandorasFox** [comment]
oh god, this refactor is gonna probably break a decent amount of stuff in people's scripts (decoupling this pretty much means I need to rearrange a _lot_ of code [which I've needed to, anyways]), so this is gonna be.... interesting....

On the bright side, the unlock indicator stuff is no longer gonna be one gigantic function, so that's a plus (and has needed to be done for a long while coming).

**Comment by PandorasFox** [comment]
This is in `dev` as of 6b943766dae08295e8ecdeb81d126e9f06f39194

I feel like there's probably a few rough edges to this refactor (since I did this in pretty much one shot), but it was mostly just copy/pasting a bunch of code around (so maybe it's fine).

(If you don't tag before building, like usual, it'll build a debug build that'll be a lot slower).

I'll poke at it more tomorrow to make sure that there's no regressions, since a lot of stuff got moved around, and a few things may have fallen between some cracks.

(also of note, a few things got broken for the sake of making stuff nicer to work with, so I'll need to update the manpage before pushing anything to master)

**Comment by PandorasFox** [comment]
Alright, I've pushed this to master and it should be working fine.

I *think* that the default I use for the status text positioning should be "right", in that the defaults and stuff should look the same. Some people might have to adjust the positioning on their rices a bit, but that was a bit unavoidable :(

**Comment by AUTplayed** [comment]
cool thanks, but I think some things are still missing in the manpage, because using cw or ch in --timepos breaks the whole positioning. Also statuspos, modifpos and indpos are just generally missing in the man page.

**Comment by PandorasFox** [comment]
Ah, yeah, cw/ch aren't variables anymore. I'll go touch those up in a bit.

The manpages really need a gigantic overhaul/redo, but I haven't really had the time to sit down and redo all the docs P:

**Comment by PandorasFox** [comment]
(Gonna close this now since I do think this is working properly now)
